### ISSUE TITLE
Unbuilt blocks still increase integrity and affect shields

### ISSUE THREAD

**Issue by kontu** [sstixrud/DefenseShields#5]
If I place a block using a single component (so the block is completely unbuilt, 0% welded basically, just barely placed); it still contributes the complete integrity value of the block to the shield.

This is a balance issue because players can place 4 dozen of a block but not spend any of the actual components and still greatly boost their shield maximum HP

**Comment by adambockey** [comment]
Would it be possible to add a check for .IsWorking to any blocks added to the Grid Integrity calculation?

**Comment by sstixrud** [comment]
fixed
