### ISSUE TITLE
Damage modulation slider does not work in multiplayer.

### ISSUE THREAD

**Issue by Allen-Wrench** [sstixrud/DefenseShields#9]
This applies only when playing on a dedicated server using this mod. 

When moving the slider to change the damage modulation setting, the detailed info in the terminal page of the modulator  _appears_ to change the value, but in fact does not. If you use the PB Api provided with the mod and get the value for the "DS-M_DamageModulation" property after moving the slider, you can see that the value does not match what is shown in the terminal. You **can** however use the programmable block to set the value of DS-M_DamageModulation directly and that does work. I believe using a timer block and terminal actions also work, so it appears to have something to do with the terminal not syncing properly with the server when a client moves the slider.

**Comment by sstixrud** [comment]
fixed
